### ISSUE TITLE
procedure table not working

### ISSUE THREAD

**Issue by calmacx** [HDRUK/CaRROT-Mapper#516]
@spco, Via Scott

## the issue

>Hi Scott

>  
> 
> I ran into an issue when running `coconnect run map`:
> 
>  
> 
> ```console
> 
> $ source coconnect-virtualenv/bin/activate
> 
> $ coconnect info version
> 
> 0.5.0
> 
> $ coconnect display dataframe hdruk-isaric_demog_hashed.csv
> 
> ...OK...
> 
> $ coconnect display dataframe hdruk-isaric_events_hashed.csv
> 
> ...OK...
> 
> ```
> 
> ```console
> 
> $ coconnect run map --rules University\ of\ Edinburgh_ISARIC4C_20220503_structural_mapping.json isaric_demog_hashed.csv isaric_events_hashed.csv
> 
> ...
> 
> 2022-05-31 12:15:45 - CommonDataModel - INFO - working on person
> 
> ...
> 
> 2022-05-31 12:15:52 - CommonDataModel - INFO - working on procedure_occurrence
> 
> 2022-05-31 12:15:52 - CommonDataModel - INFO - starting on Oxygen therapy 4374
> 
> 2022-05-31 12:15:52 - ProcedureOccurrence - INFO - Called apply_rules
> 
> 2022-05-31 12:15:52 - LocalDataCollection - INFO - Retrieving initial dataframe for 'isaric_events_hashed.csv' for the first time
> 
> 2022-05-31 12:15:52 - ProcedureOccurrence - INFO - Mapped person_id
> 
> 2022-05-31 12:15:53 - ProcedureOccurrence - INFO - Mapped procedure_concept_id
> 
> 2022-05-31 12:15:53 - ProcedureOccurrence - INFO - Mapped procedure_datetime
> 
> 2022-05-31 12:15:53 - ProcedureOccurrence - INFO - Mapped procedure_source_concept_id
> 
> 2022-05-31 12:15:53 - ProcedureOccurrence - INFO - Mapped procedure_source_value
> 
> 2022-05-31 12:15:53 - ProcedureOccurrence - INFO - Automatically formatting data columns.
> 
> 2022-05-31 12:15:55 - ProcedureOccurrence - INFO - created df (0x7f72407e7c88)[Oxygen_therapy_4374]
> 
> Traceback (most recent call last):
> 
>   File "/home/hdruk_data/coconnect-virtualenv/lib64/python3.6/site-packages/pandas/core/indexes/base.py", line 2898, in get_loc
> 
>     return self._engine.get_loc(casted_key)
> 
>   File "pandas/_libs/index.pyx", line 70, in pandas._libs.index.IndexEngine.get_loc
> 
>   File "pandas/_libs/index.pyx", line 101, in pandas._libs.index.IndexEngine.get_loc
> 
>   File "pandas/_libs/hashtable_class_helper.pxi", line 1675, in pandas._libs.hashtable.PyObjectHashTable.get_item
> 
>   File "pandas/_libs/hashtable_class_helper.pxi", line 1683, in pandas._libs.hashtable.PyObjectHashTable.get_item
> 
> KeyError: 'procedure_start_date'
> 
>  
> 
> The above exception was the direct cause of the following exception:
> 
>  
> 
> Traceback (most recent call last):
> 
>   File "/home/hdruk_data/coconnect-virtualenv/bin/coconnect", line 8, in <module>
> 
>     sys.exit(coconnect())
> 
>   File "/home/hdruk_data/coconnect-virtualenv/lib/python3.6/site-packages/click/core.py", line 1128, in __call__
> 
>     return self.main(*args, **kwargs)
> 
>   File "/home/hdruk_data/coconnect-virtualenv/lib/python3.6/site-packages/click/core.py", line 1053, in main
> 
>     rv = self.invoke(ctx)
> 
>   File "/home/hdruk_data/coconnect-virtualenv/lib/python3.6/site-packages/click/core.py", line 1659, in invoke
> 
>     return _process_result(sub_ctx.command.invoke(sub_ctx))
> 
>   File "/home/hdruk_data/coconnect-virtualenv/lib/python3.6/site-packages/click/core.py", line 1659, in invoke
> 
>     return _process_result(sub_ctx.command.invoke(sub_ctx))
> 
>   File "/home/hdruk_data/coconnect-virtualenv/lib/python3.6/site-packages/click/core.py", line 1395, in invoke
> 
>     return ctx.invoke(self.callback, **ctx.params)
> 
>   File "/home/hdruk_data/coconnect-virtualenv/lib/python3.6/site-packages/click/core.py", line 754, in invoke
> 
>     return __callback(*args, **kwargs)
> 
>   File "/home/hdruk_data/coconnect-virtualenv/lib/python3.6/site-packages/click/decorators.py", line 26, in new_func
> 
>     return f(get_current_context(), *args, **kwargs)
> 
>   File "/home/hdruk_data/coconnect-virtualenv/lib/python3.6/site-packages/coconnect/cli/subcommands/run.py", line 569, in map
> 
>     cdm.process(conserve_memory=True)
> 
>   File "/home/hdruk_data/coconnect-virtualenv/lib/python3.6/site-packages/coconnect/cdm/model.py", line 654, in process
> 
>     for j,obj in enumerate(df_generator):
> 
>   File "/home/hdruk_data/coconnect-virtualenv/lib/python3.6/site-packages/coconnect/cdm/model.py", line 820, in process_table
> 
>     df = obj.get_df(start_index=start_index)
> 
>   File "/home/hdruk_data/coconnect-virtualenv/lib/python3.6/site-packages/coconnect/cdm/objects/versions/v5_3_1/procedure_occurrence.py", line 44, in get_df
> 
>     if df['procedure_start_date'].isnull().all():
> 
>   File "/home/hdruk_data/coconnect-virtualenv/lib64/python3.6/site-packages/pandas/core/frame.py", line 2906, in __getitem__
> 
>     indexer = self.columns.get_loc(key)
> 
>   File "/home/hdruk_data/coconnect-virtualenv/lib64/python3.6/site-packages/pandas/core/indexes/base.py", line 2900, in get_loc
> 
>     raise KeyError(key) from err
> 
> KeyError: 'procedure_start_date'
> 
> $ ls output_data/
> 
> person_ids.tsv  person.tsv
> 
> ```
> 
>  
> 
> Any ideas?

## the solution

This isn't an issue with the ETL Tool but the generation of the rules json  for the procedure table by the web-app that is getting the name wrong. I can see a quick fix, but the procedure table hasnt been smoke tested properly (which I am working on now)

**Comment by calmacx** [comment]
Hmm 
```
'procedure_occurrence':['procedure_datetime'],
```

potentially a false alarm, and really the issue is coming from the python tool.....

**Comment by calmacx** [comment]
False alarm indeed, sorry for the noise, it is the python tool
